<Project Sdk="Remora.Resonite.Sdk/2.3.1">
  <PropertyGroup>
    <PackageId>ComponentSelectorAdditions</PackageId>
    <Title>Component Selector Additions</Title>
    <Authors>Banane9</Authors>
    <Version>0.10.1-beta</Version>
    <Description>This MonkeyLoader mod for Resonite overhauls the Component Selector / Protoflux Node Selector to have a search, as well as favorites and recents categories.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ResoniteModdingGroup/ComponentSelectorAdditions</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <PackageTags>mod; mods; monkeyloader; resonite; component; attacher; selector; protoflux; node; picker; search; favorites</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="Locale\*" Pack="true" PackagePath="content/Locale/" />
  </ItemGroup>

  <ItemGroup>
    <ResoniteReference Include="Elements.Assets" />
    <ResoniteReference Include="Elements.Core" />
    <ResoniteReference Include="Elements.Quantity" />
    <ResoniteReference Include="FrooxEngine" />
    <ResoniteReference Include="Renderite.Shared" />
  </ItemGroup>
</Project>
